// =============================================================
// models/Checkout.js
// PURPOSE: Final car return process (Module 5 - Kulathunga).
// KEY MATH in checkoutController:
//   kmsDriven       = endOdometer - Car.startingOdometer
//   overLimitKms    = max(0, kmsDriven - Car.maxKmAllowed)
//   overLimitCharge = overLimitKms × Car.extraKmChargePerKm
//   damagePenalty   = linked SOSAlert.estimatedDamageCost
//   finalBill       = Booking.totalPrice + addOnsAtCheckout + overLimitCharge + damagePenalty
// PDF generated by pdfkit with itemised breakdown.
// =============================================================

const mongoose = require('mongoose');

const CheckoutSchema = new mongoose.Schema(
  {
    // ----- Relationships -----
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    booking: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Booking',
      required: true,
    },

    car: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Car',
      required: true,
    },

    // Link to any SOS/accident from this trip (for damage penalty)
    sosAlert: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'SOSAlert',
      default: null,
    },

    // ----- Odometer -----
    // Starting odometer was recorded on the Car document when booking was approved
    startOdometer: {
      type: Number,
      required: [true, 'Start odometer is required'],
    },

    endOdometer: {
      type: Number,
      required: [true, 'End odometer reading is required'],
    },

    // Computed: endOdometer − startOdometer
    kmsDriven: {
      type: Number,
    },

    // ----- PHOTO: Dashboard Odometer (Multer – Module 5) -----
    odometerPhoto: {
      type: String, // e.g. 'uploads/checkout/odometer_xyz.jpg'
      required: [true, 'Odometer photo is required'],
    },

    // ----- Over-Limit Detection -----
    maxKmAllowed: {
      type: Number,
      default: 0, // 0 means no limit was set
    },

    overLimitKms: {
      type: Number,
      default: 0,
    },

    overLimitCharge: {
      type: Number,
      default: 0,
    },

    // ----- Extra Charges at Checkout (e.g., GPS rental $10) -----
    extraCharges: [
      {
        description: String, // e.g. "GPS Rental"
        amount: Number,      // e.g. 10
      },
    ],

    extraChargesTotal: {
      type: Number,
      default: 0,
    },

    // ----- Damage Penalty (from SOS Module) -----
    damagePenalty: {
      type: Number,
      default: 0,
    },

    // ----- Final Bill -----
    // bookingBasePrice  = original Booking.totalPrice
    bookingBasePrice: {
      type: Number,
    },

    // finalBill = bookingBasePrice + extraChargesTotal + overLimitCharge + damagePenalty
    finalBill: {
      type: Number,
    },

    // ----- Condition Notes -----
    // Staff remarks on car condition at return
    conditionNotes: {
      type: String,
      trim: true,
    },

    // ----- PDF Checkout Bill -----
    // Path to the generated final bill PDF
    checkoutPdfPath: {
      type: String,
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('Checkout', CheckoutSchema);
